### ISSUE TITLE
probability filters

### ISSUE THREAD

**Issue by BjornBeckmann** [NERC-CEH/irecord-grasshoppers-app#1]
Hi Karolis and Vilius, the app is looking fantastic, thanks so much! If there is time, please add the probability filters based on week and 10km square, like in iRecord Butterflies. I have created the files, attached here - I hope all as required! The hectads file is the same as for the butterflies, the other two are new for the grasshoppers. Let me know if there are any issues or questions at all. Many thanks!

[grasshopper_hectad_counts_per_week.csv](https://github.com/NERC-CEH/irecord-grasshoppers-app/files/10475165/grasshopper_hectad_counts_per_week.csv)
[hectads.csv](https://github.com/NERC-CEH/irecord-grasshoppers-app/files/10475166/hectads.csv)
[grasshopper_species.csv](https://github.com/NERC-CEH/irecord-grasshoppers-app/files/10475167/grasshopper_species.csv)

**Comment by Vilius-Stankaitis** [comment]
- Add options in the settings 
- Add stickers to species guide

**Comment by Vilius-Stankaitis** [comment]
Hi @BjornBeckmann,

It is done now. Would be possible if you could take a look and see if it correct? 
https://grasshoppers.app.flumens.io/demo.html

I have added "admin" settings in the app->settings page ( only in the demo app ), you can change current  hectad and week.
![Screenshot 2023-01-24 at 15.53.36.png](https://zube.io/files/nerc-ceh/50028773f2a917bc592852b0b1fb88b0-screenshot-2023-01-24-at-15-53-36.png)

**Comment by BjornBeckmann** [comment]
@Vilius-Stankaitis Hi Vilius, thanks so much, very exciting! I had a look and it looks really great already! 

I have two suggested edits for sorting species, which would be great to implement if possible (instead of alphabetical sorting).

I attach a new version of the "grasshopper_species.csv" file, where I have added numbers for sorting in the "type" column, and a new column called "commonness", which is simply a sum of all records for each species. 

If possible, could you make the following changes to the sorting: 

1) In all sections (Now in your area, In your area at other times of year, Species not recorded from your area) could the species be sorted first by "type", i.e. 1grasshopper, 2earwig, 3cockroach etc.

2) Then within each "type", for Now in your area use the sorting as currently implemented, i.e. sort by number of records for the current week, which is great. For In your area at other times and Species not recorded from your area, sort each "type" by "commonness" in descending order, i.e. commonest grasshoppers at the top, and within the earwigs commonest earwig at the top etc.

3) If users turn smart species lists off, then it would be great if the sorting could also be first by type, then within each type by commonness.

I hope that makes sense and might be feasible? Many species are very rare and unlikely to be seen, and it would be very helpful if they are moved to the bottom of each list and the common ones to the top. However no worries and I completely understand if this isn't possible currently!

Many thanks,
Bjorn

[grasshopper_species.csv](https://github.com/NERC-CEH/irecord-grasshoppers-app/files/10494176/grasshopper_species.csv)

**Comment by Vilius-Stankaitis** [comment]
@BjornBeckmann I have implemented new changes. Could you check if they are correct?

https://grasshoppers.app.flumens.io/demo.html

**Comment by BjornBeckmann** [comment]
Great, thanks so much, looks perfect!

All the best,
Bjorn
