### ISSUE TITLE
phenology diagrams

### ISSUE THREAD

**Issue by BjornBeckmann** [NERC-CEH/irecord-grasshoppers-app#2]
These would potentially be great to add to the "When to see" section - but completely understand if no time, no problem!

Link to files: at https://www.dropbox.com/sh/53vsqxfxs62n0ut/AADnYosDxbgnQQgcbe3KxCfPa?dl=0. There are two versions - lighter and darker colours, please choose which you prefer, or let me know colours to use and I can easily rerun the diagrams - also a different file format if preferable?

There are more species here than currently in the app, and a few Latin names are different. Let me know if you will implement this and I will create a file mapping the names to the app names?

**Comment by kazlauskis** [comment]
Thanks, we'll add these in.

**Comment by Vilius-Stankaitis** [comment]
@BjornBeckmann Done now but for some species phenology diagrams and "When to see" don't match.

**Comment by BjornBeckmann** [comment]
@Vilius-Stankaitis 

Thanks so much Vilius, it looks great! 

I will check the texts along with the others, probably some are out of date...

When I click on a diagram to view it larger, it rotates by 90 degrees (so it goes top to bottom on the screen, not left to right). Is this intentional? Might be ok? But I guess this is just on a laptop, and on a phone you can pinch and zoom...?

![image](https://user-images.githubusercontent.com/42246650/214433315-231a300b-62cc-47d4-ab9f-ea15eed05fcb.png)

Many thanks again and all the best,
Bjorn

**Comment by Vilius-Stankaitis** [comment]
Yes, rotation is intentional, lifechart looks very compressed if positioned left to right.

**Comment by BjornBeckmann** [comment]
Ok, sounds good, thanks!
